---

- block:
    - name: '038 | 安装ntp服务'
      ansible.builtin.package:
        name: ntp
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      when: ansible_os_family == "Debian" or
            (ansible_os_family == "RedHat" and
            ansible_distribution_major_version == '7')
      tags: ntp_install

    - name: '039 | copy ntp.conf'
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
      notify: "restart ntp"
      when: ansible_os_family == "Debian"
      tags: ntp_conf

    - name:  '039 | copy ntp.conf'
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
      notify: "restart ntpd"
      when: ansible_os_family == "RedHat" and
            ansible_distribution_major_version == '7'
      tags: ntp_conf

    - name: '040 | 安装chrony服务'
      ansible.builtin.package:
        name: chrony
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      tags: ntp_install
      when: ansible_os_family == "RedHat" and
            ansible_distribution_major_version >= '8'

    - name: '041 | copy chrony.conf'
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
      notify: "restart chronyd"
      tags: ntp_conf
      when: ansible_os_family == "RedHat" and
            ansible_distribution_major_version >= '8'
  when: ntp_enabled is defined and ntp_enabled|bool
  tags: ntp


...
