---

- name: '034 | 替换hosts解析'
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item }}"
    line: "{{ item }}"
    unsafe_writes: true  # to prevent failures in CI
  loop: "{{ etc_hosts }}"
  when:
    - etc_hosts is defined
    - etc_hosts | length > 0
  tags: etc_hosts
- name: "finaly | 测试结束"
  fail:
    msg: "完成测试"
  when: 1 == 1
...
