---

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers

- block:
    - name: '035 | 设置内核参数变量'
      ansible.builtin.set_fact:
        sysctl_conf_dynamic_var: "{{ sysctl_conf_dynamic_var | default([]) + (sysctl_conf[item] | default([]) | flatten(1)) }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"

    - name: '036 | 设置内核参数'
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
      loop: "{{ sysctl_conf_dynamic_var | default([]) | unique }}"
      when: sysctl_conf_dynamic_var | default([]) | length > 0
  ignore_errors: true
  when: sysctl_set|bool
  tags: sysctl, kernel


...
